[package]
name = "live-reload"
version = "0.1.0"
edition = "2024"

[dependencies]
uncovr = { path = "../.." }
tokio = { version = "1.35", features = ["full"] }
tower-livereload = "0.9"
serde = { version = "1.0", features = ["derive"] }
tracing-subscriber = "0.3"
tera = "1.19"
